#!/usr/bin/env python3
"""Generate logos.txt — the distro logo bundle used by the dashboard.

Logos come from fastfetch (MIT, https://github.com/fastfetch-cli/fastfetch).
Only logos that fit next to the info column are kept (small variant preferred).

    python3 tools/gen-logos.py /path/to/fastfetch-source > logos.txt

Bundle format (one block per logo):
    @ <alias> <alias> ...          os-release IDs / names this logo is used for
    = <sgr1> <sgr2> ...            SGR colors for $1 $2 … (e.g. 31, 38;5;208)
    <logo lines with $1..$9 color markers>
"""
import os, re, sys, glob

MAX_W, MAX_H = 36, 18
TARGET_W, TARGET_H = 30, 13
MIN_H = 8
# extra os-release IDs -> logo they should use (when fastfetch has no logo under that ID)
EXTRA = {"sles": "suse", "sled": "suse", "sles_sap": "suse", "opensuse": "opensuse-tumbleweed",
         "archarm": "arch", "rhel": "redhat", "ol": "oracle"}
src = sys.argv[1]
ascii_dir = os.path.join(src, "src/logo/ascii")

colors_h = open(os.path.join(src, "src/common/color.h")).read()
MACROS = dict(re.findall(r'#define (FF_COLOR_[A-Z0-9_]+) "([^"]*)"', colors_h))

def color_expr(expr):
    # e.g.  FF_COLOR_FG_256 "208"   |  FF_COLOR_FG_RED  |  FF_COLOR_MODE_BOLD FF_COLOR_FG_RED
    out = ""
    for tok in re.findall(r'FF_COLOR_[A-Z0-9_]+|"[^"]*"', expr):
        out += tok.strip('"') if tok.startswith('"') else MACROS.get(tok, "")
    return out or "39"

# macro name -> text file, e.g. FASTFETCH_DATATEXT_LOGO_UBUNTU_SMALL -> u/ubuntu_small.txt
files = {}
for f in glob.glob(os.path.join(ascii_dir, "*", "*.txt")):
    key = "FASTFETCH_DATATEXT_LOGO_" + re.sub(r"[^A-Z0-9]", "_", os.path.basename(f)[:-4].upper())
    files[key] = f

entries = []
for inc in sorted(glob.glob(os.path.join(ascii_dir, "*.inc"))):
    text = open(inc).read()
    for block in re.findall(r"\{\s*\.names\s*=.*?\n    \},", text, re.S):
        names = re.findall(r'"([^"]+)"', re.search(r"\.names\s*=\s*\{([^}]*)\}", block).group(1))
        m = re.search(r"\.lines\s*=\s*(\w+)", block)
        if not m or m.group(1) not in files:
            continue
        cm = re.search(r"\.colors\s*=\s*\{(.*?)\}", block, re.S)
        colors = [color_expr(c) for c in cm.group(1).split(",") if c.strip()] if cm else []
        tm = re.search(r"\.type\s*=\s*([^,\n]+)", block)
        typ = tm.group(1) if tm else ""
        lines = open(files[m.group(1)]).read().rstrip("\n").split("\n")
        vis = [re.sub(r"\$\d", "", l).rstrip() for l in lines]
        entries.append(dict(names=[n.lower().replace(" ", "-") for n in names], small="SMALL" in typ,
                            alter="ALTER" in typ, lines=[l.rstrip() for l in lines],
                            w=max(len(v) for v in vis), h=len(lines), colors=colors or ["39"]))

def base(n):
    return re.sub(r"[_-]small$", "", n)

# group by base alias; pick the best-fitting logo for each
best = {}
for e in entries:
    for n in e["names"]:
        b = base(n)
        if e["w"] > MAX_W or e["h"] > MAX_H:
            continue
        cur = best.get(b)
        # prefer non-alternate art, then by tier:
        #   0: fits the header's natural size (TARGET) and isn't tiny -> the largest such
        #   1: fits MAX and isn't tiny -> the most compact such
        #   2: anything that fits (tiny)  -> the largest such
        area = e["h"] * e["w"]
        if e["w"] <= TARGET_W and e["h"] <= TARGET_H and e["h"] >= MIN_H: score = (e["alter"], 0, -area)
        elif e["h"] >= MIN_H:                                              score = (e["alter"], 1, area)
        else:                                                              score = (e["alter"], 2, -area)
        if cur is None or score < cur[0]:
            best[b] = (score, e)

for extra, target in EXTRA.items():
    if extra not in best and target in best:
        best[extra] = best[target]

# aliases that logos-custom.txt provides itself
CUSTOM = set()
_c = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logos-custom.txt")
if os.path.exists(_c):
    for l in open(_c):
        if l.startswith("@ "): CUSTOM.update(l.split()[1:])

# emit: group aliases that share the same logo
by_logo = {}
for b, (_, e) in sorted(best.items()):
    by_logo.setdefault(id(e), (e, []))[1].append(b)

print("# awesome-ssh-login-screen distro logos — generated by tools/gen-logos.py")
print("# logo art from fastfetch https://github.com/fastfetch-cli/fastfetch, under its MIT license:")
print("#")
for line in open(os.path.join(src, "LICENSE")).read().rstrip("\n").split("\n"):   # MIT asks for the notice to travel with the art
    print(("# " + line).rstrip())
print("#")
# hand-made logos first (they win over fastfetch ones with the same alias)
custom = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logos-custom.txt")
if os.path.exists(custom):
    sys.stdout.write(open(custom).read())
for e, aliases in sorted(by_logo.values(), key=lambda x: x[1][0]):
    aliases = [a for a in aliases if a not in CUSTOM]   # overridden by logos-custom.txt
    if not aliases:
        continue
    print("@ " + " ".join(sorted(aliases)))
    print("= " + " ".join(e["colors"]))
    print("\n".join(e["lines"]))
